name: Build EXE

on:
  workflow_dispatch:   # Se ejecuta manualmente desde Actions

jobs:
  build:
    runs-on: windows-latest   # Usa Windows (para que compile .exe)

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile mi_programa.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mi_programa-exe
        path: dist/mi_programa.exe
